# Generated by Django 4.1.5 on 2023-02-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.RenameModel(
            old_name='Phones',
            new_name='PhoneModel',
        ),
        migrations.AddField(
            model_name='infomodel',
            name='name1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phonemodel'),
        ),
    ]
