# Generated by Django 4.1.5 on 2023-02-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_infomodel_delete_info_rename_phones_phonemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phonemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='InfoModel',
        ),
    ]
